language: node_js
node_js:
- '5.11'

before_deploy:
  - echo "DEPLOY STAGING"
  on:
    branch: staging


deploy:
  - provider: codedeploy
    access_key_id: AKIAJ253F7NSZKJ2KCTA
    secret_access_key:
      secure: f4/1gbNucWVdFKaMl0RvrUYYh84MIEe/qKWOliJwIRJ0mRvDOOpQfGo15nzhGAhXw9CRvy3T3WnhItQuPWhYoVwx18RUJMbuLsxXXHRM1B2RB+XRh1jQ/ajmTl4MQ+pQFaU7R+c3JQE4KFUY9f/TBNVk35cC/edK89/W8D4mz8/HVAXJxeZtUaUnigFOubhWP8/UcXBXgN2ZIMdGEYWhVxr689GTOwWf8De6bqfnNX5hkXAb/xQss3u4h+dIwJ4MaU6iwreKgTLXHePlrbrX37yKcOwTCYlkiS15lGVjwzfe8Lw32504xiNIfb/WWIP7lAkSu0hrgrI8lwFHwT6+DflCHqXk9J6KuwlWcJCTdjDjoGFxBGVlZNXOT2mKpXQ4B3mNbBjZJKUVqOZv+9qp2rhvBtx/Il3yRGyQWnL9GF5LPNd0hg1mXz8dIn3zWnWg1OslHs9FHGcYN8TsRqTfrPDfA7Y27gaytVkiiIanAy/i70QtB0cKHUeSvhykK04ZI8sLM3Lc0Kw6725QyDmxKEz9P297XEZH1+Ohw5MwFtEUKJYZpwXG73YxUi+ovrLhpuukXP7nJpzXNiIcOb2jm818msgNjwfE7mrvCM+wJks377u2NFJ0FnlcoosCQctP3Rou8q3VnDuUip9RX2H8zEearBfxlGCJvaUXlKV2KkI=
    revision_type: github
    application: DemoApplicationJG
    deployment_group: testProd
    region: eu-west-1
    wait-until-deployed: true
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAJ253F7NSZKJ2KCTA
    secret_access_key:
      secure: f4/1gbNucWVdFKaMl0RvrUYYh84MIEe/qKWOliJwIRJ0mRvDOOpQfGo15nzhGAhXw9CRvy3T3WnhItQuPWhYoVwx18RUJMbuLsxXXHRM1B2RB+XRh1jQ/ajmTl4MQ+pQFaU7R+c3JQE4KFUY9f/TBNVk35cC/edK89/W8D4mz8/HVAXJxeZtUaUnigFOubhWP8/UcXBXgN2ZIMdGEYWhVxr689GTOwWf8De6bqfnNX5hkXAb/xQss3u4h+dIwJ4MaU6iwreKgTLXHePlrbrX37yKcOwTCYlkiS15lGVjwzfe8Lw32504xiNIfb/WWIP7lAkSu0hrgrI8lwFHwT6+DflCHqXk9J6KuwlWcJCTdjDjoGFxBGVlZNXOT2mKpXQ4B3mNbBjZJKUVqOZv+9qp2rhvBtx/Il3yRGyQWnL9GF5LPNd0hg1mXz8dIn3zWnWg1OslHs9FHGcYN8TsRqTfrPDfA7Y27gaytVkiiIanAy/i70QtB0cKHUeSvhykK04ZI8sLM3Lc0Kw6725QyDmxKEz9P297XEZH1+Ohw5MwFtEUKJYZpwXG73YxUi+ovrLhpuukXP7nJpzXNiIcOb2jm818msgNjwfE7mrvCM+wJks377u2NFJ0FnlcoosCQctP3Rou8q3VnDuUip9RX2H8zEearBfxlGCJvaUXlKV2KkI=
    revision_type: github
    application: DemoApplicationJG
    deployment_group: testStaging
    region: eu-west-1
    wait-until-deployed: true
    on:
      branch: staging
